blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogView, BlogDeleteView, BlogUserListView, BlogListView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<slug:slug>', BlogView.as_view(), name='view_blog'),
    path('blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='delete_blog'),
    path('blogs/user/', BlogUserListView.as_view(), name='user_list_blog'),
    path('blogs/', BlogListView.as_view(), name='list_blog'),
    path('blog/update/<slug:slug>', BlogUpdateView.as_view(), name='update_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import *

app_name = MainConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('rights_content/', RightsContentView.as_view(), name='rights_content'),
    path('appointment/create/', AppointmentCreateView.as_view(), name='create_appointment'),

    # Список записей принадлежащих авторизованному пользователю
    path('appointments/user/', AppointmentUserListView.as_view(), name='appointments_user'),

    # Список все записей
    path('appointments/', AppointmentListView.as_view(), name='appointments'),

    # Список записей врача
    path('appointments/doctor/', AppointmentDoctorListView.as_view(), name='appointments_doctor'),

    path('patient/profile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
    path('appointment/delete/<int:pk>', AppointmentDeleteView.as_view(), name='delete_appointment'),

    path('feedback/create/', FeedbackCreateView.as_view(), name='create_feedback'),
    path('feedback/user/', FeedbackUserListView.as_view(), name='user_list_feedback'),
    path('feedback/all/', FeedbackListView.as_view(), name='list_feedback'),
    path('feedback/delete/<int:pk>', FeedbackDeleteView.as_view(), name='delete_feedback'),
]

blog/models.py
from django.db import models

from config import settings
from services.utils import unique_slugify, NULLABLE


class Blog(models.Model):
    """ Модель статьи (блога) """
    name = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=255, verbose_name='url')
    content = models.TextField(max_length=1500, verbose_name='содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    date_time = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    publication = models.BooleanField(default=False, verbose_name='признак публикации')
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        verbose_name='Владелец',
        **NULLABLE
    )
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.name}'

    def delete(self, using=None, keep_parents=False):
        """ Удаление статьи """
        self.publication = False
        self.save()

    def save(self, *args, **kwargs):
        """ Сохранение полей модели при их отсутствии заполнения """
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django import forms

from blog.models import Blog
from services.forms import FormStyleMixin


class BlogCreateForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('name', 'content', 'image')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView

from blog.forms import BlogCreateForm
from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    """ Создание блога """
    model = Blog
    form_class = BlogCreateForm

    def get_success_url(self):
        """ Берем slug из данного объекта """
        return reverse_lazy('blog:view_blog', args=(self.object.slug,))

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """
        # Создает форму в памяти, без отправки в бд
        self.object = form.save(commit=False)
        # Передает текущего пользователя в user
        self.object.owner = self.request.user
        # Сохраняет в бд
        self.object.save()
        return super(BlogCreateView, self).form_valid(form)


class BlogView(DetailView):
    """ Отображение блога """
    model = Blog

    def get_object(self, queryset=None):
        """ Получает объект, увеличивает просмотры """
        object_blog = super().get_object()
        object_blog.number_of_views += 1
        object_blog.save()
        return object_blog


class BlogUserListView(LoginRequiredMixin, ListView):
    """ Все блоги данного пользователя """
    model = Blog
    template_name = 'blog/blog_user_list.html'

    def get_queryset(self):
        """ Получает статьи текущего пользователя """
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user) & queryset.filter(publication=True)
        return queryset


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление блога """
    model = Blog
    success_url = reverse_lazy('blog:user_list_blog')


class BlogListView(ListView):
    """ Все статьи с активной публикацией """
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(publication=True)
        return queryset


class BlogUpdateView(UpdateView):
    """ Обновление блога """
    model = Blog
    form_class = BlogCreateForm
    success_url = reverse_lazy('blog:user_list_blog')

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

{% if object.owner == user %}

<!-- Start Page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Удаление публикации</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Удаление публикации</span></p>
            </div>
        </div>
    </div>
<!-- End Page Title Section -->

<!-- Start My Profile Section -->
    <div id="profile-page" class="layer-stretch">
        <div class="layer-wrapper">
            <div class="theme-material-card text-center">
                <form method="post">
                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-8">
                        <div class="theme-block theme-block-hover">

                            {% csrf_token %}
                            <h3>Уверены, что хотите удалить публикацию?</h3><br><br>
                            Название: {{ object.name }}<BR>
                            Дата создания: {{ object.date_time }}<BR>

                        </div>
                    </div>
                    <div class="col-md-2">
                    </div>
                </div>
                <div class="form-submit">
                    <input type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect button button-danger" value="Подтвердите удаление">
                </div>
                </form>
            </div>
        </div>
    </div><!-- End My Profile Section -->

{% else %}

{% include 'main/404.html' %}

{% endif %}

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% load FilterExtension %}
{% block content %}


<!-- Start Page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Просмотр публикации</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <a href="{% url 'blog:user_list_blog' %}">Все публикации</a> &#8594; <span>Публикация</span></p>
            </div>
        </div>
    </div><!-- End Page Title Section -->
    <!-- Start Blog Section -->
    <div class="layer-stretch">
        <div class="layer-wrapper">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8 text-center">
                    <div class="theme-material-card">
                        <div class="theme-img blog-picture">
                            <img class="" src="{{ object.image|mediapath }}" alt="">
                        </div>
                        <h2 class="blog-ttl">{{ object.name }}</h2>
                        <ul class="blog-detail">
                            <li><i class="fa fa-user-o"></i>{{ object.owner.first_name }} {{ object.owner.last_name }}</li>
                            <li><i class="fa fa-calendar-o"></i>{{ object.date_time }}</li>
                            <li>Просмотров: {{ object.number_of_views }}</li>
                        </ul>
                        <div class="blog-post">
                            <p>{{ object.content }}</p>
                        </div>
                        <div class="row blog-meta">
                            <div class="col-sm-7 blog-tag">
                                {% if object.owner == user %}
                                <a href="{% url 'blog:delete_blog' object.slug %}">Удалить</a>&nbsp&nbsp&nbsp
                                <a href="{% url 'blog:update_blog' object.slug %}">Редактировать</a>
                                {% endif %}
                            </div>
                            <div class="col-sm-5 text-right">
                                <ul class="social-list social-list-sm">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                    <li><a href="#"><i class="fa fa-flickr"></i></a></li>
                                    <li><a href="#"><i class="fa fa-rss"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2"></div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}
{% load FilterExtension %}
{% block content %}

{% if user.is_authenticated %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Опубликовать статью</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Публикация статьи</span></p>
            </div>
        </div>
    </div>
    <div id="profile-page" class="layer-stretch">

        <div class="layer-wrapper">
            <div class="theme-material-card text-center">
                <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-8 ">

                        <h3>
                            {% csrf_token %}
                            {% for field in form %}
                            <div>
                                {{ field.label_tag }}
                                {{ field|feedback_form }}<BR>
                                {% if field.errors %}
                                {{ field.errors|striptags }}
                                {% endif %}
                            </div>
                            {% endfor %}
                        </h3>

                    </div>
                </div>
                <div class="form-submit">
                    <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect button button-primary">Опубликовать</button>
                </div>
                </form>
            </div>
        </div>
    </div>

{% else %}

{% include 'main/404.html' %}

{% endif %}

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% load FilterExtension %}
{% block content %}

    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Мои публикации</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Мои публикации</span></p>
            </div>
        </div>
    </div>

    <!-- Start Blog List Section -->
    <div class="layer-stretch">
        <div class="layer-wrapper text-center">
            <div class="row">

                {% if blog_list %}
                {% for blog in blog_list %}
                <div class="col-md-6 col-lg-4">
                    <div class="theme-block theme-block-hover">
                        <div class="theme-block-picture">
                            <div class="blog-card-date">{{ blog.date_time }}</div>
                            <img src="{{ blog.image|mediapath }}" alt="">
                        </div>
                        <div class="blog-card-ttl">
                            <h3><a href="{% url 'blog:view_blog' blog.slug %}">{{ blog.name }}</a></h3>
                        </div>
                        <div class="blog-card-details">
                            <p><i class="fa fa-user-o"></i>{{ blog.owner.first_name }} {{ blog.owner.last_name }}</p>
                            <p><a href="{% url 'blog:view_blog' blog.slug %}" class="mdl-button mdl-js-button mdl-js-ripple-effect">Читать дальше</a></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class="col-lg-12">
                    <h2>Публикаций пока нет!</h2>
                </div>
                {% endif %}

            </div>
        </div>
    </div><!-- End Blog List Section -->

{% endblock %}

blog/templates/blog/blog_user_list.html
{% extends 'main/base.html' %}
{% load FilterExtension %}
{% block content %}

    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Мои публикации</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Мои публикации</span></p>
            </div>
        </div>
    </div>

    <!-- Start Blog List Section -->
    <div class="layer-stretch">
        <div class="layer-wrapper text-center">
            <div class="row">

                {% if blog_list %}
                {% for blog in blog_list %}
                <div class="col-md-6 col-lg-4">
                    <div class="theme-block theme-block-hover">
                        <div class="theme-block-picture">
                            <div class="blog-card-date">{{ blog.date_time }}</div>
                            <img src="{{ blog.image|mediapath }}" alt="">
                        </div>
                        <div class="blog-card-ttl">
                            <h3><a href="{% url 'blog:view_blog' blog.slug %}">{{ blog.name }}</a></h3>
                        </div>
                        <div class="blog-card-details">
                            <p><i class="fa fa-user-o"></i>{{ blog.owner.first_name }} {{ blog.owner.last_name }}</p>
                            <p><a href="{% url 'blog:view_blog' blog.slug %}" class="mdl-button mdl-js-button mdl-js-ripple-effect">Читать дальше</a></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class="col-lg-12">
                    <h2>У вас пока нет публикаций!<BR>
                    Либо ваша статья находится на проверке администрации сайта.</h2>
                </div>
                {% endif %}

            </div>
        </div>
    </div><!-- End Blog List Section -->

{% endblock %}