blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogView, BlogDeleteView, BlogUserListView, BlogListView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<slug:slug>', BlogView.as_view(), name='view_blog'),
    path('blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='delete_blog'),
    path('blogs/user/', BlogUserListView.as_view(), name='user_list_blog'),
    path('blogs/', BlogListView.as_view(), name='list_blog'),
    path('blog/update/<slug:slug>', BlogUpdateView.as_view(), name='update_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import *

app_name = MainConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('rights_content/', RightsContentView.as_view(), name='rights_content'),
    path('appointment/create/', AppointmentCreateView.as_view(), name='create_appointment'),

    # Список записей принадлежащих авторизованному пользователю
    path('appointments/user/', AppointmentUserListView.as_view(), name='appointments_user'),

    # Список все записей
    path('appointments/', AppointmentListView.as_view(), name='appointments'),

    # Список записей врача
    path('appointments/doctor/', AppointmentDoctorListView.as_view(), name='appointments_doctor'),

    path('patient/profile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
    path('appointment/delete/<int:pk>', AppointmentDeleteView.as_view(), name='delete_appointment'),

    path('feedback/create/', FeedbackCreateView.as_view(), name='create_feedback'),
    path('feedback/user/', FeedbackUserListView.as_view(), name='user_list_feedback'),
    path('feedback/all/', FeedbackListView.as_view(), name='list_feedback'),
    path('feedback/delete/<int:pk>', FeedbackDeleteView.as_view(), name='delete_feedback'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.forms import UserLoginForm
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', UserActivate.as_view(), name='verify_email'),
    path('user_activate', TemplateView.as_view(template_name='users/user_activate.html'), name='user_activate'),
    path('invalid_user_activate/', InvalidUserActivate.as_view(), name='invalid_user_activate'),
    path('reset_password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update', ProfileUpdateView.as_view(), name='profile_update'),
]

users/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, UserManager as UserBaseManager
from django.db import models
from django.apps import apps

from services.utils import NULLABLE


class UserManager(UserBaseManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label,
            self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class RoleStatus(models.TextChoices):
    """ Класс описание статуса пользователя доктор или пациент """
    DOCTOR = 'DOCTOR'
    PATIENT = 'PATIENT'


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    email_verify = models.BooleanField(default=False)
    role_status = models.CharField(
        max_length=7,
        choices=RoleStatus.choices,
        default=RoleStatus.PATIENT,
        verbose_name='Статус пользователя (доктор или пациент)'
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField

from services.forms import FormStyleMixin
from users.models import User


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'class': 'mdl-textfield__input',
                'placeholder': 'Email',
                'id': 'login-email'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'mdl-textfield__input',
                'placeholder': 'Password',
                'id': 'login-password',
            }
        )
    )


class UserForm(FormStyleMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetDoneView, PasswordContextMixin
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import UpdateView, CreateView, FormView, TemplateView
from pip._internal.utils._jaraco_text import _

from main.forms import PatientForm
from main.models import Patient
from services.utils import generation_password
from config import settings
from users.forms import UserRegisterForm, UserForm
from users.models import User
from django.forms import inlineformset_factory


class RegisterView(CreateView):
    """ Регистрация пользователя """
    model = User
    form_class = UserRegisterForm

    def form_valid(self, form):
        """ Дружественное письмо на почту пользователя, после регистрации """
        # Работа с пользователем
        new_user = form.save()
        uid = urlsafe_base64_encode(force_bytes(new_user.pk))
        new_token = token_generator.make_token(new_user)
        activation_url = reverse_lazy('users:verify_email', kwargs={'uidb64': uid, 'token': new_token})
        send_mail(
            subject='Центр медицинской диагностики - Активация учетной записи',
            message=f'Убедительная просьба: если хотите закончить регистрацию, пройдите по ссылке: http://37.143.13.164:8000/{ activation_url }',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
            fail_silently=False
        )
        return redirect('users:confirm_email')


class UserActivate(View):
    """ Активация пользователя из письма """
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        # Сравнение токенов
        if user is not None and token_generator.check_token(user, token):
            # Создает пациента данному пользователю (Запись в БД)
            Patient.objects.create(
                owner=user
            )
            # В случае удачи, активирует нового пользователя флагом True, сохраняет обЪект, логинится и отправляет письмо на почту
            user.email_verify = True
            user.save()
            login(request, user)
            send_mail(
                subject='Центр медицинской диагностики - Успешная активация',
                message=f'Вы успешно активировали учетную запись!\nС уважением администрация сервиса.',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email]
            )
            return redirect('users:user_activate')
        return redirect('users:invalid_user_activate')

    @staticmethod
    def get_user(uidb64):
        """ Получение пользователя """
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None
        return user


class InvalidUserActivate(TemplateView):
    """ Случай неудачной активации """
    template_name = 'users/invalid_user_activate.html'


class UserPasswordResetView(PasswordContextMixin, FormView):
    """ Сброс пароля, генерация нового с отправкой на email """
    form_class = PasswordResetForm
    success_url = reverse_lazy("users:password_reset_done")
    title = _("Password reset")
    template_name = 'users/password_reset_form.html'

    def form_valid(self, form):
        """ Получает email, по email получает пользователя, генерирует и присваивает новый пароль,
        отправляет пароль на почту  """
        user_email: str = self.request.POST.get('email')
        new_password: str = generation_password()
        user_object: object = User.objects.get(email=user_email)
        send_mail(
            subject='Центр медицинской диагностики - Восстановление пароля',
            message=f'Вас приветствует администрация Центра медицинской диагностики.\nВы запросили новый пароль для {user_email}.\nВаш новый пароль: {new_password}\nС уважением администрация Центра медицинской диагностики.',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user_email]
        )
        user_object.set_password(new_password)
        user_object.save()
        return super().form_valid(form)


class UserPasswordResetDoneView(PasswordResetDoneView):
    PasswordResetDoneView.template_name = 'users/password_reset_done.html'


class ProfileView(TemplateView):
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        """ Делает набор данных из раззных моделей """
        context_data = super().get_context_data(**kwargs)

        # Получает, пациента по пользователю
        patient = Patient.objects.filter(owner=self.request.user)
        if patient:
            patient = patient[0]
        # Передает пациента в context_data
        context_data['patient'] = patient

        return context_data


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирование профиля """
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    # def get_success_url(self, *args, **kwargs):
    #     return reverse('users:profile_update', args=[self.get_object().pk])

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        Patientformset = inlineformset_factory(User, Patient, form=PatientForm, extra=0)
        if self.request.method == 'POST':
            context_data['formset'] = Patientformset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = Patientformset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

users/templates/users/confirm_email.html
{% extends 'main/base.html' %}
{% block content %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Регистрация на портале</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Регистрация</span></p>
            </div>
        </div>
    </div>
<!-- End page Title Section -->
<!-- Start Login Section -->
    <div id="login-page" class="layer-stretch">
        <div class="layer-wrapper">
            <div class="form-container">
                <h5>Регистрация прошла успешно!</h5>
                Вам на почту отправлена ссылка, для подтверждения регистрации. Пожалуйста, проверьте почту!
            </div>
        </div>
    </div>
<!-- End Login Section -->

{% endblock %}

users/templates/users/invalid_user_activate.html
{% extends 'main/base.html' %}
{% block content %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Активация пользователя</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Активация</span></p>
            </div>
        </div>
    </div>
<!-- End page Title Section -->
<!-- Start Login Section -->
    <div id="login-page" class="layer-stretch">
        <div class="layer-wrapper">
            <div class="form-container">
                <h5>Ошибка верификации!</h5>
                Ваша ссылка устарела или неправильно указан почтовый адрес.
            </div>
            <div class="login-link">
                <a href="{% url 'users:register' %}" class="">Зарегистрироваться</a>
            </div>
        </div>
    </div>
<!-- End Login Section -->

{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load FilterExtension %}
{% block content %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Вход в портал</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Вход</span></p>
            </div>
        </div>
    </div>
<!-- End page Title Section -->
<!-- Start Login Section -->
    <div id="login-page" class="layer-stretch">
        <div class="layer-wrapper">
            <div class="form-container">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p|login_form }}
                    <div class="text-right">
                        <a href="{% url 'users:reset_password' %}">Забыли пароль?</a>
                    </div>
                    <div class="form-submit">
                        <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect button button-primary">Войти</button>
                    </div>
                </form>
                <div class="or-using">Войти через аккаунт</div>
                <div class="social-login">
                    <a href="#" class="social-facebook"><i class="fa fa-facebook"></i>Facebook</a>
                    <a href="#" class="social-google"><i class="fa fa-google"></i>Google</a>
                </div>
                <div class="login-link">
                    <span class="paragraph-small">Нет аккаунта?</span>
                    <a href="{% url 'users:register' %}" class="">Зарегистрироваться</a>
                </div>
            </div>
        </div>
    </div>
<!-- End Login Section -->

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'main/base.html' %}
{% block content %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Смена пароля</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Смена пароля</span></p>
            </div>
        </div>
    </div>
<!-- End page Title Section -->
<!-- Start Login Section -->
    <div id="login-page" class="layer-stretch">
        <div class="layer-wrapper">
            <div class="form-container">
                <h5>Смена пароля прошла успешно!</h5>
                Мы отправили вам новый пароль на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.
            Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.
            </div>
            <div class="login-link">
                <a href="{% url 'users:login' %}" class="">Войти</a>
            </div>
        </div>
    </div>
<!-- End Login Section -->

{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'main/base.html' %}
{% load FilterExtension %}
{% block content %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Смена пароля</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Смена пароля</span></p>
            </div>
        </div>
    </div>
<!-- End page Title Section -->
<!-- Start Login Section -->
    <div id="login-page" class="layer-stretch">
        <div class="layer-wrapper">
            <div class="form-container">
                <h5>Адрес электронной почты:</h5>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p|reset_password_form }}
                    <div class="form-submit">
                        <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect button button-primary">Отправить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<!-- End Login Section -->

{% endblock %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}
{% load FilterExtension %}

{% block content %}

<!-- Start Page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Мой профиль</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Мой профиль</span></p>
            </div>
        </div>
    </div>
<!-- End Page Title Section -->

<!-- Start My Profile Section -->
    <div id="profile-page" class="layer-stretch">
        <div class="layer-wrapper">
            <div class="theme-material-card text-center">
                <div class="row">
                    <div class="col-md-4">
                        <div class="theme-block theme-block-hover">
                            <div class="theme-block-picture">
                                {% if user.avatar %}
                                    <img style="width: 350px;" src="{{ user.avatar|mediapath }}" alt="Avatar">
                                {% else %}
                                    <img style="width: 300px;" src="{% static 'images/no_foto.jpg' %}" alt="Not Avatar">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-user-o"></i>
                            <span class="primary-color">{{ user.first_name }}</span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-user-o"></i>
                            <span class="primary-color">{{ user.last_name }}</span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-phone"></i>
                            <span class="primary-color">{{ user.phone }}</span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-map-marker"></i>
                            <span class="primary-color">{{ user.country }}</span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-envelope-o"></i>
                            <span class="primary-color">{{ user.email }}</span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-calendar"></i>
                            <span class="primary-color">
                                {% if patient.birthday %}
                                    {{ patient.birthday }}
                                {% else %}
                                    не заполнено
                                {% endif %}
                            </span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-address-card"></i>
                            <span class="primary-color">
                                {% if patient.address %}
                                    {{ patient.address }}
                                {% else %}
                                    не заполнено
                                {% endif %}
                            </span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label form-input-icon">
                            <i class="fa fa-tint"></i>
                            <span class="primary-color">
                                {% if patient.blood_type %}
                                    {{ patient.blood_type }}
                                {% else %}
                                    не заполнено
                                {% endif %}
                            </span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label form-input-icon">
                            <i class="fa fa-male"></i>
                            <span class="primary-color">
                                {% if patient.gender %}
                                    {{ patient.gender }}
                                {% else %}
                                    не заполнено
                                {% endif %}
                            </span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-history"></i>
                            <span class="primary-color">
                                {% if patient.place_of_work %}
                                    {{ patient.place_of_work }}
                                {% else %}
                                    не заполнено
                                {% endif %}
                            </span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-futbol-o"></i>
                            <span class="primary-color">
                                {% if patient.hobbies %}
                                    {{ patient.hobbies }}
                                {% else %}
                                    не заполнено
                                {% endif %}
                            </span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                            <i class="fa fa-superpowers"></i>
                            <span class="primary-color">
                                {% if patient.discount_status %}
                                    Скидка на услуги: {{ patient.discount_status }}%
                                {% else %}
                                    не заполнено
                                {% endif %}
                            </span>
                            <p class=" mdl-textfield__input"></p>
                        </div>
                    </div>
                </div>
                <div class="form-submit">
                    <a href="{% url 'users:profile_update' %}" class="mdl-button mdl-js-button mdl-js-ripple-effect button button-primary">Изменить профиль</a>
                </div>
            </div>
        </div>
    </div><!-- End My Profile Section -->

{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}
{% load FilterExtension %}
{% block content %}

{% if user.is_authenticated %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Обновление профиля</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Обновление профиля</span></p>
            </div>
        </div>
    </div>
    <div id="profile-page" class="layer-stretch">

        <div class="layer-wrapper">
            <div class="theme-material-card text-center">
                <form method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-4">

                    {% csrf_token %}
                    {{ form.as_p|update_form }}

                    </div>
                    <div class="col-md-4">

                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p|update_form }}
                        {% endfor %}

                    </div>
                </div>
                <div class="form-submit">
                    <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect button button-primary">Сохранить</button>
                </div>
            </div>
        </div>
    </div>

<!-- End page Title Section -->

{% else %}

<!-- Start page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Регистрация пользователя</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Регистрация</span></p>
            </div>
        </div>
    </div>
<!-- End page Title Section -->
<!-- Start Register Section -->
    <div class="layer-stretch">
        <div class="layer-wrapper">
            <div class="form-container">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p|registration_form }}
                    <div class="form-submit">
                        <button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect button button-primary">Зарегистрироваться</button>
                    </div>
                </form>
                <div class="or-using">Войти через аккаунт</div>
                <div class="social-login">
                    <a href="#" class="social-facebook"><i class="fa fa-facebook"></i>Facebook</a>
                    <a href="#" class="social-google"><i class="fa fa-google"></i>Google</a>
                </div>
                <div class="login-link">
                    <span class="paragraph-small">Аккаунт создан?</span>
                    <a href="{% url 'users:login' %}" class="">Войти</a>
                </div>
            </div>
        </div>
    </div>
<!-- End Register Section -->

{% endif %}

{% endblock %}