blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogView, BlogDeleteView, BlogUserListView, BlogListView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<slug:slug>', BlogView.as_view(), name='view_blog'),
    path('blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='delete_blog'),
    path('blogs/user/', BlogUserListView.as_view(), name='user_list_blog'),
    path('blogs/', BlogListView.as_view(), name='list_blog'),
    path('blog/update/<slug:slug>', BlogUpdateView.as_view(), name='update_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import *

app_name = MainConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('rights_content/', RightsContentView.as_view(), name='rights_content'),
    path('appointment/create/', AppointmentCreateView.as_view(), name='create_appointment'),

    # Список записей принадлежащих авторизованному пользователю
    path('appointments/user/', AppointmentUserListView.as_view(), name='appointments_user'),

    # Список все записей
    path('appointments/', AppointmentListView.as_view(), name='appointments'),

    # Список записей врача
    path('appointments/doctor/', AppointmentDoctorListView.as_view(), name='appointments_doctor'),

    path('patient/profile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
    path('appointment/delete/<int:pk>', AppointmentDeleteView.as_view(), name='delete_appointment'),

    path('feedback/create/', FeedbackCreateView.as_view(), name='create_feedback'),
    path('feedback/user/', FeedbackUserListView.as_view(), name='user_list_feedback'),
    path('feedback/all/', FeedbackListView.as_view(), name='list_feedback'),
    path('feedback/delete/<int:pk>', FeedbackDeleteView.as_view(), name='delete_feedback'),
]

main/models.py
import datetime

from django.db import models
from config import settings
from services.utils import NULLABLE


class Department(models.Model):
    """ Модель отделения клиники (гинекология) """
    name = models.CharField(max_length=150, verbose_name='Название отделения (например кардиология)')

    def __str__(self):
        return f'Отдел: {self.name}'

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'


class Post(models.Model):
    """ Модель должности (санитар) """
    name = models.CharField(max_length=150, verbose_name='Должность (например акушер)')
    department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name='Отдел которому принадлежит должность'
    )

    def __str__(self):
        return f'Должность: {self.name}. {self.department}'

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'


class Doctor(models.Model):
    """ Модель сущности доктора """
    post = models.ForeignKey(
        Post,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Должность'
    )
    education = models.CharField(max_length=255, verbose_name='Образование', **NULLABLE)
    awards = models.CharField(max_length=255, verbose_name='Награды', **NULLABLE)
    experience = models.DateField(verbose_name='Стаж с "дата"', **NULLABLE)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name='Владелец'
    )
    status_appointment = models.BooleanField(
        default=True,
        verbose_name='Статус врача, True - можно записаться на прем',
        **NULLABLE
    )

    def __str__(self):
        return f'{self.post}'

    class Meta:
        verbose_name = 'Врач'
        verbose_name_plural = 'Врачи'


class BloodType(models.TextChoices):
    """ Группа крови """
    ONE_NEGATIVE = 'O(|) Rh-'
    ONE_POSITIVE = 'O(|) Rh+'
    TWO_NEGATIVE = 'A(||) Rh-'
    TWO_POSITIVE = 'A(||) Rh+'
    THREE_NEGATIVE = 'B(|||) Rh-'
    THREE_POSITIVE = 'B(|||) Rh+'
    FOUR_NEGATIVE = 'AB(|V) Rh-'
    FOUR_POSITIVE = 'AB(|V) Rh+'


class GenderChoice(models.TextChoices):
    """ Пол пациента """
    FEMALE = 'женщина'
    MALE = 'мужчина'


class Patient(models.Model):
    """ Модель сущности пациента """
    birthday = models.DateField(verbose_name='День рождения', **NULLABLE)
    address = models.CharField(max_length=255, verbose_name='Адресс проживания', **NULLABLE)
    blood_type = models.CharField(
        max_length=10,
        choices=BloodType.choices,
        verbose_name='Группа крови',
        **NULLABLE
    )
    gender = models.CharField(
        max_length=7,
        choices=GenderChoice.choices,
        verbose_name='Пол пациента',
        **NULLABLE
    )
    place_of_work = models.CharField(max_length=255, verbose_name='Место работы', **NULLABLE)
    hobbies = models.CharField(max_length=255, verbose_name='Увлечения', **NULLABLE)
    discount_status = models.SmallIntegerField(verbose_name='Скидка пациента на услуги', default=0)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name='Владелец'
    )

    def __str__(self):
        return f'{self.owner}'

    class Meta:
        verbose_name = 'Пациент'
        verbose_name_plural = 'Пациенты'


class Time(models.Model):
    """ Время приема """
    time = models.TimeField(verbose_name='Время для записи на прием')

    def __str__(self):
        return f'{self.time}'

    class Meta:
        verbose_name = 'Время приема'
        verbose_name_plural = 'Время приема'


class StatusAppointment(models.TextChoices):
    """ Статус записи на прием """
    ACTIVE = 'Активный'
    CANCEL = 'Отменён'
    COMPLETED = 'Завершен'


class Appointment(models.Model):
    """ Запись пациента на прием """
    date = models.DateField(**NULLABLE, verbose_name='Дата приема')
    time = models.ForeignKey(
        Time,
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name='Время приема')
    doctor = models.ForeignKey(
        Doctor,
        related_name='doctor_name',
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name='Врач'
    )
    status = models.CharField(
        max_length=8,
        choices=StatusAppointment.choices,
        verbose_name='Статус записи на прием',
        default=StatusAppointment.ACTIVE
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name='Владелец'
    )

    def __str__(self):
        return f'{self.doctor}'

    class Meta:
        verbose_name = 'Запись на прием'
        verbose_name_plural = 'Записи на прием'


class Feedback(models.Model):
    """ Модель - Отзыв о клинике """
    text = models.TextField(max_length=1500, verbose_name='Отзыв о центре медицинской диагностики')
    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Отображать отзыв о клинике')
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        verbose_name='Владелец',
        **NULLABLE
    )

    def __str__(self):
        return f'{self.owner}'

    class Meta:
        verbose_name = 'Отзыв клиента (пациента)'
        verbose_name_plural = 'Отзывы клиентов (пациентов)'

main/forms.py
from django import forms
from django.core.exceptions import ValidationError

from main.models import Patient, Appointment, Feedback
from services.forms import FormStyleMixin


class PatientForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('__all__')


class AppointmentForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('date', 'time', 'doctor')

    def clean_doctor(self):
        date = self.cleaned_data['date']
        time = self.cleaned_data['time']
        doctor = self.cleaned_data['doctor']
        doctor_bd = Appointment.objects.filter(doctor=doctor)\
                    & Appointment.objects.filter(date=date)\
                    & Appointment.objects.filter(time=time)
        if doctor_bd:
            raise ValidationError('Извините, запись на данное время уже существует!')

        return doctor


class FeedbackForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('text',)

main/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, DeleteView, DetailView

from blog.models import Blog
from main.forms import AppointmentForm, FeedbackForm
from main.models import Doctor, Appointment, Time, Patient, Feedback
from services.utils import calendar_line_to_list
from users.models import User


# Create your views here.
class HomeView(ListView):
    """ Главная страница """
    model = User
    template_name = 'main/home.html'
    extra_context = {
        'title': ''
    }

    def get_context_data(self, **kwargs):
        """ Делает набор данных из раззных моделей """
        context_data = super().get_context_data(**kwargs)

        # Передает в doctors объекты докторов
        # Получает, всех докторов
        doctor_list = Doctor.objects.all()
        # Количество выводимых врачей
        count: int = 5
        count_doctor = Doctor.objects.all().count()
        if count_doctor < count:
            count = count_doctor
        # Список случайных объектов (Докторов)
        doctor_random_list: list = []
        # В случае существования докторов в БД
        if doctor_list:
            doctor_random_list = random.sample(list(doctor_list), count)
        context_data['doctors'] = doctor_random_list

        # Передает в feedbacks объекты отзывов
        # Получает, все отзывы
        feedback_list = Feedback.objects.filter(is_active=True)
        # Количество выводимых отзывов
        count: int = 5
        count_feedback = Feedback.objects.filter(is_active=True).count()
        if count_feedback < count:
            count = count_feedback
        # Список случайных объектов (Отзывы)
        feedback_random_list: list = []
        # В случае существования отзывов в БД
        if feedback_list:
            feedback_random_list = random.sample(list(feedback_list), count)
        context_data['feedbacks'] = feedback_random_list

        # Передает в feedbacks объекты отзывов
        # Получает, все отзывы
        blog_list = Blog.objects.filter(publication=True).order_by("-date_time")
        blog_list_: list = []
        if blog_list.count() >= 2:
            blog_list_.append(blog_list[0])
            blog_list_.append(blog_list[1])
        context_data['blog_list'] = blog_list_

        return context_data


class RightsContentView(TemplateView):
    """  """
    template_name = 'main/rights_content.html'


class AppointmentCreateView(LoginRequiredMixin, CreateView):
    """ Создание записи на прием """
    model = Appointment
    form_class = AppointmentForm

    def get_success_url(self):
        """ Берем id из данного объекта """
        return reverse_lazy('main:appointments_user')

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """
        # Создает форму в памяти, без отправки в бд
        self.object = form.save(commit=False)
        # Передает текущего пользователя в user
        self.object.owner = self.request.user
        # Сохраняет в бд
        self.object.save()

        return super(AppointmentCreateView, self).form_valid(form)


class AppointmentUserListView(LoginRequiredMixin, ListView):
    """ Список записей принадлежащих авторизованному пользователю """
    model = Appointment

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        """ Делает набор данных из раззных моделей """
        context_data = super().get_context_data(**kwargs)

        # Передача календаря
        days, year, month, day, month_int = calendar_line_to_list()
        context_data['days'] = days
        context_data['year'] = year
        context_data['month'] = month
        context_data['day_now'] = day

        return context_data


class AppointmentListView(ListView):
    """ Список всех записей """
    model = Appointment
    template_name = 'main/appointment_list_all.html'

    def get_context_data(self, **kwargs):
        """ Делает набор данных из раззных моделей """
        context_data = super().get_context_data(**kwargs)

        # Передача календаря
        days, year, month, day, month_int = calendar_line_to_list()
        context_data['days'] = days
        context_data['year'] = year
        context_data['month'] = month
        context_data['day_now'] = day

        # Передает всех врачей
        doctors = Doctor.objects.all()
        context_data['doctors_list'] = doctors

        # Передает время
        times = Time.objects.all()
        context_data['times_list'] = times

        return context_data


class AppointmentDoctorListView(LoginRequiredMixin, ListView):
    """ Список записей для врача """
    model = Appointment
    template_name = 'main/appointment_list_doctor.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        doctor = Doctor.objects.filter(owner=self.request.user)
        queryset = queryset.filter(doctor=doctor[0])
        return queryset

    def get_context_data(self, **kwargs):
        """ Делает набор данных из раззных моделей """
        context_data = super().get_context_data(**kwargs)

        # Передача календаря
        days, year, month, day, month_int = calendar_line_to_list()
        context_data['days'] = days
        context_data['year'] = year
        context_data['month'] = month
        context_data['day_now'] = day

        # Передает время
        times = Time.objects.all()
        context_data['times_list'] = times

        return context_data


class UserProfileView(LoginRequiredMixin, DetailView):
    """ Просмотр профиля пациента, фитча для врача """
    model = User
    template_name = 'main/user_profile.html'

    def get_context_data(self, **kwargs):
        """ Делает набор данных из раззных моделей """
        context_data = super().get_context_data(**kwargs)

        # Передача календаря
        user = context_data['object']
        patient = Patient.objects.filter(owner=user)
        context_data['patient'] = patient[0]

        return context_data


class AppointmentDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление записи """
    model = Appointment
    success_url = reverse_lazy('main:appointments_user')


class FeedbackCreateView(LoginRequiredMixin, CreateView):
    """ Создание отзыва пользователя """
    model = Feedback
    form_class = FeedbackForm

    def get_success_url(self):
        """ Редирект на страницу """
        return reverse_lazy('main:user_list_feedback')

    def form_valid(self, form):
        """ Автоматически сохраняет текущего пользователя в поле user """
        # Создает форму в памяти, без отправки в бд
        self.object = form.save(commit=False)
        # Передает текущего пользователя в user
        self.object.owner = self.request.user
        # Сохраняет в бд
        self.object.save()

        return super(FeedbackCreateView, self).form_valid(form)


class FeedbackUserListView(LoginRequiredMixin, ListView):
    """ Просмотр отзывов данного пользователя """
    model = Feedback
    template_name = 'main/feedback_user_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = Feedback.objects.filter(owner=self.request.user)
        return queryset


class FeedbackDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление записи """
    model = Feedback
    success_url = reverse_lazy('main:user_list_feedback')


class FeedbackListView(LoginRequiredMixin, ListView):
    """ Просмотр отзывов всех пользователей """
    model = Feedback
    template_name = 'main/feedback_list.html'

main/templates/main/appointment_list.html
{% extends 'main/base.html' %}
{% load static %}
{% load FilterExtension %}
{% block content %}

<!-- Start Page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Мои записи</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Обзор моих записей на прием</span></p>
            </div>
        </div>
    </div>
    <!-- End Page Title Section -->
    <!-- Start Event Calendar Section -->
    <div class="layer-stretch">
        <div class="layer-wrapper">
            <div class="row">
                <div class="col-md-8">
                    <div class="theme-material-card">
                        <h3>{{ month }} {{ year }}</h3>
                        <table class="table table-bordered">
                            <thead>
                                <tr class="table-primary-head text-center">
                                    <th style="width: 100px">Понедельник</th>
                                    <th style="width: 100px">Вторник</th>
                                    <th style="width: 100px">Среда</th>
                                    <th style="width: 100px">Четверг</th>
                                    <th style="width: 100px">Пятница</th>
                                    <th style="width: 100px">Суббота</th>
                                    <th style="width: 100px">Воскресенье</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    {% for day in days %}
                                        {% if day == 0 %}
                                            </tr>
                                            <tr>
                                        {% else %}
                                            <td {% if day == day_now %} class="table-info" {% endif %} style="height: 100px; text-align: center">
                                                {{ day }}
                                                <BR>
                                                {% for appointment in object_list %}
                                                    {% if day == appointment.date|date_modified %}

                                                        <!-- Start appointment Modal -->
                                                        <div id="{{ appointment.time|time_modified }}" class="modal fade" role="dialog">
                                                            <div class="modal-dialog">
                                                                <div class="modal-content">
                                                                    <div class="modal-header text-center">
                                                                        <h5 class="modal-title">Запись на прием</h5>
                                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                    </div>
                                                                    <div class="modal-body text-left">
                                                                        <div class="table-primary p-3">
                                                                            <span class="paragraph-medium">
                                                                                <span class="text-dark text-left">Прием назначен на: {{ month }} {{ year }} года {{ day }} числа</span>
                                                                                <span>Время приема: {{ appointment.time|time_seconds_modified }} часов</span>
                                                                            </span>
                                                                        </div>
                                                                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label form-input-icon">
                                                                            <img class="img-responsive" style="width: 300px" src="{{ appointment.doctor.owner.avatar|mediapath }}" alt="{{ appointment.doctor.owner.last_name }} {{ appointment.doctor.owner.first_name }}"><br>
                                                                            Вас примет: {{ appointment.doctor.owner.last_name }} {{ appointment.doctor.owner.first_name }}<BR>
                                                                            {{ appointment.doctor.post.name }}<BR>
                                                                            {{ appointment.doctor.post.department }}<BR><BR>
                                                                            Статус записи: {{ appointment.status }}<BR><BR>
                                                                            <a href="{% url 'main:delete_appointment' appointment.id %}" class="alert-dark">Отменить запись</a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <!-- End appointment Modal -->
                                                        <div class="table-primary">
                                                            <a data-toggle="modal" data-target="#{{ appointment.time|time_modified }}">{{ appointment.time|time_seconds_modified }}</a><br>
                                                        </div>

                                                    {% endif %}
                                                {% endfor %}
                                            </td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- Start blogds post -->
                <div class="col-md-4">
                    <div class="theme-material-card">
                        <div class="sub-ttl">Latest News</div>
                        <a href="#" class="row blog-recent">
                            <div class="col-4 blog-recent-img">
                                <img class="img-responsive img-thumbnail" src="uploads/recent-1.jpg" alt="">
                            </div>
                            <div class="col-8 blog-recent-post">
                                <h4>Why Food Poisoning happened and How To</h4>
                                <p>08 Jun 2017</p>
                            </div>
                        </a>
                        <a href="#" class="row blog-recent">
                            <div class="col-4 blog-recent-img">
                                <img class="img-responsive img-thumbnail" src="uploads/recent-2.jpg" alt="">
                            </div>
                            <div class="col-8 blog-recent-post">
                                <h4>Which Healthy Food Fads Should You Follow?</h4>
                                <p>27 Apr 2017</p>
                            </div>
                        </a>
                        <a href="#" class="row blog-recent">
                            <div class="col-4 blog-recent-img">
                                <img class="img-responsive img-thumbnail" src="uploads/recent-3.jpg" alt="">
                            </div>
                            <div class="col-8 blog-recent-post">
                                <h4>A Broken Heart Can Hurt More Than You Think</h4>
                                <p>29 Jan 2017</p>
                            </div>
                        </a>
                        <a href="#" class="row blog-recent">
                            <div class="col-4 blog-recent-img">
                                <img class="img-responsive img-thumbnail" src="uploads/recent-4.jpg" alt="">
                            </div>
                            <div class="col-8 blog-recent-post">
                                <h4>Keep it Clean: Make Sure Your Fruits and Veggies</h4>
                                <p>24 Jan 2017</p>
                            </div>
                        </a>
                        <a href="#" class="row blog-recent">
                            <div class="col-4 blog-recent-img">
                                <img class="img-responsive img-thumbnail" src="uploads/recent-5.jpg" alt="">
                            </div>
                            <div class="col-8 blog-recent-post">
                                <h4>Should I bring my child in for a routine physical?</h4>
                                <p>15 Jan 2017</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- End Event Calendar Section -->
    <!-- Start Modal for event -->
    <div id="event-popup" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h4 class="modal-title font-20">Popup Heading</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">

                    <p class="paragraph-medium paragraph-black event-ttl">
                        <span class="theme-dropcap primary-color">E</span>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam earum, provident ad, porro aperiam dolore, blanditiis, nihil pariatur eius adipisci consequuntur officiis. Excepturi, nostrum? Id incidunt nesciunt officia hic distinctio.
                    </p>
                    <p class="paragraph-medium paragraph-black event-ttl">
                        Est wisi interpretaris te. Velit oblique vel ex, mea sanctus blandit quaerendum ea, cu movet viris posidonium cum. Ea expetenda repudiandae sit. No animal facilisi conclusionemque pri, cetero reprehendunt te sed. Tale zril veniam pro id, eum eu mucius accusata maluisset. Nemore regione facilisis est te, eius scripta delectus ne eum.
                    </p>
                    <p class="font-16 color-orange event-date text-right"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
<!-- End Modal for event -->

{% endblock %}

main/templates/main/feedback_list.html
{% extends 'main/base.html' %}
{% block content %}

<!-- Start Page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Отзывы пользователей</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Отзывы</span></p>
            </div>
        </div>
    </div>
<!-- End Page Title Section -->

<div id="accordion">

    <div class="theme-material-card">
        <div class="theme-accordion-container">
            {% for object in object_list %}
            <div class="theme-accordion">
                <div class="theme-accordion-hdr">
                    <h4 class="color-green"><i class="fa fa-stethoscope"></i>{{ object.date_time }}</h4>
                    <div class="theme-accordion-control"><i class="fa fa-plus"></i></div>
                </div>
                <div class="theme-accordion-bdy">
                    <div class="row service-accordian">
                        <div class="col-sm-3 theme-accordian-img text-center">
                        </div>
                        <div class="col-sm-6">
                            <p class="paragraph-small paragraph-black">
                                {{ object.text }}
                            </p>
                            <div class="pull-right">
                                {% if object.owner == user %}
                                <a class="anchor-icon" href="{% url 'main:delete_feedback' object.id %}">Удалить<i class="fa fa-arrow-right"></i></a>
                                {% endif%}
                            </div>
                        </div>
                        <div class="col-sm-3 theme-accordian-img text-center">
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/feedback_user_list.html
{% extends 'main/base.html' %}
{% block content %}

<!-- Start Page Title Section -->
    <div class="page-ttl">
        <div class="layer-stretch">
            <div class="page-ttl-container">
                <h1>Мои отзывы</h1>
                <p><a href="{% url 'main:home' %}">Главная</a> &#8594; <span>Мои отзывы</span></p>
            </div>
        </div>
    </div>
<!-- End Page Title Section -->

<div id="accordion">

    <div class="theme-material-card">
        <div class="theme-accordion-container">
            {% for object in object_list %}
            <div class="theme-accordion">
                <div class="theme-accordion-hdr">
                    <h4 class="color-green"><i class="fa fa-stethoscope"></i>{{ object.date_time }}</h4>
                    <div class="theme-accordion-control"><i class="fa fa-plus"></i></div>
                </div>
                <div class="theme-accordion-bdy">
                    <div class="row service-accordian">
                        <div class="col-sm-3 theme-accordian-img text-center">
                        </div>
                        <div class="col-sm-6">
                            <p class="paragraph-small paragraph-black">
                                {{ object.text }}
                            </p>
                            <div class="pull-right">
                                <a class="anchor-icon" href="{% url 'main:delete_feedback' object.id %}">Удалить<i class="fa fa-arrow-right"></i></a>
                            </div>
                        </div>
                        <div class="col-sm-3 theme-accordian-img text-center">
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}